### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [NudeDude/ZoomView#1]
Hi again @NudeDude  here's what I came up with for this project. If you like it, I will make a PR again with the files :) 

![pres-01](https://user-images.githubusercontent.com/36028424/55722618-5b207400-5a39-11e9-8a93-907f6ae891bf.png)

**Comment by NudeDude** [comment]
This logo looks great I like it :)

**Comment by Tobaloidee** [comment]
That's great! Which color do you prefer? So that i can finalize it and make a PR

**Comment by NudeDude** [comment]
The red one looks great

**Comment by Tobaloidee** [comment]
Here's the PR #2 @NudeDude  and also you can download the other versions & formats of your logo [HERE](https://drive.google.com/drive/u/1/folders/1VKZ_GiZouMSYcqWptl-aP0zGQcAErmIw) on the link to my drive..

Thanks a lot for accepting and allowing me to design to all your projects! If you need me in the future just mention me. 💯 Best regards! 

-Tobaloidee

**Comment by NudeDude** [comment]
Thank you very much @Tobaloidee for your work :-)

**Comment by NudeDude** [comment]
Thank you very much @Tobaloidee for your work :-)
